apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiburr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiburr
  template:
    metadata:
      labels:
        app: kaiburr
    spec:
      containers:
        - name: spring-app
          image: kaiburr-kaiburr-app
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/docker-db
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kaiburr
spec:
  selector:
    app: knote
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer