version: "3.8"
services:
  kaiburr-app:
    build: .
    container_name: "spring-app"
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
